// src/utils/anamneseConfig.js

export const labelMap = {
  // 1) INFORMAÇÕES DE DADOS PESSOAIS
  nome: "Nome:",
  idade: "Idade:",
  dataNascimento: "Data de Nascimento:",
  naturalidade: "Naturalidade:",
  nacionalidade: "Nacionalidade",
  nomeMae: "Mãe:",
  idadeMae: "Idade:",
  profissaoMae: "Profissão:",
  nomePai: "Pai:",
  idadePai: "Idade:",
  profissaoPai: "Profissão:",
  irmaos: "Irmãos (nome e idade):",
  // 2) QUEIXA PRINCIPAL
  queixaPrincipal: "Queixa Principal",
  sexo: "Sexo:",
  // 3) GESTAÇÃO E CONCEPÇÃO
  queriaEngravidar: "Você queria engravidar?",
  gestacao: "Como foi a gestação?",
  fezPreNatal: "Fez tratamento pré-natal?",
  periodoGestacao: "Período de Gestação:",
  apgar: "APGAR:",
  fezIngestaoToxicos: "Fez ingestão de tóxicos?",
  parto: "Como foi o parto:",
  cordaoUmbilical: "Nasceu com o cordão umbilical enrolado no pescoço?",
  chorouAoNascer: "Chorou ao nascer?",
  // 4) AMAMENTAÇÃO E ALIMENTAÇÃO
  mamouPeito: "Mamou no peito?",
  mamouPeitoAteIdade: "Até que idade?",
  hojeTemHoraParaComer: "Hoje tem hora para comer?",
  comeComIndependencia: "Come com independência?",
  desdeIdadeCome: "Desde que idade?",
  fazUsoTalher: "Faz uso de talher?",
  derramaAlimentos: "Derrama alimentos ou suco?",
  comemJuntos: "Comem juntos?",
  porqueNaoComeJunto: "Porque?",
  recursosMesa:
    "São necessários recursos para manter seu filho sentado à mesa?",
  restricaoAlimentar: "Seu filho possui alguma restrição alimentar?",
  quaisRestricoes: "Quais?",
  // 5) DESENVOLVIMENTO PSICOMOTOR
  idadePsicomotor: "Com que idade?",
  engatinhou: "Engatinhou?",
  fixouCabeca: "Fixou a cabeça?",
  sorriu: "Sorriu?",
  sentouSozinho: "Sentou sozinho?",
  andouSozinho: "Andou Sozinho?",
  caiaMuito: "Caia muito?",
  // 6) CONTROLE DE ESFÍNCTERES
  controleEsfincteres: "Possuí controle de esfíncteres?",
  idadeParouFraldas: "Com qual idade parou de usar fraldas?",
  controlaFezesDiurnas: "Controla fezes diurnas?",
  controlaFezesNoturnas: "Controla fezes noturnas?",
  controlaUrinaDiurnas: "Controla urina diurnas?",
  controlaUrinaNoturnas: "Controla urina noturnas?",
  pedeParaIrOuVaiSozinho: "Pede para ir ao banheiro ou vai sozinho?",
  tomaBanhoSozinho: "Toma banho sozinho?",
  vesteSeSozinho: "Veste-se e despe-se sozinho?",
  usaFraldas: "Usa fraldas?",
  tentouTirarFraldas: "Já tentou tirar?",
  dificuldadesEncontradas: "Quais dificuldades foram encontradas?",
  // 7) COMUNICAÇÃO VERBAL
  falaFuncional: "Possui fala funcional?",
  primeirasPalavrasIdade:
    "Com quantos anos começou a falar as primeiras palavras?",
  falaFrasesCompletas: "Fala frases completas?",
  anosFrases: "Com quantos anos começou a usar as frases?",
  falaSignificativa: "Usa fala significativa?",
  entendeFala: "Você entende o que ele(a) conta?",
  temComecoMeioEFim: "Tem começo, meio e fim?",
  consegueDarRecado: "Consegue dar um recado?",
  consegueManterDialogo: "Consegue manter um diálogo?",
  questionamentosExcessivos:
    "Possui questionamentos ou preocupações excessivas?",
  linguagemIncompreensivel: "Possui linguagem incompreensível?",
  emiteGritos: "Emite gritos ou barulhos complexos semelhantes à fala?",
  ecolalia: "Apresenta ecolalia?",
  usoPersistentePalavrasFrases:
    "Apresenta uso persistente de algumas palavras reconhecíveis ou frases?",
  gagueira: "Gagueira?",
  trocaDeLetras: "Troca de letras?",
  // 8) COMUNICAÇÃO NÃO-VERBAL
  indicaApontando: "Indica apontando com os dedos as suas vontades?",
  expressaNaoVerbalmente:
    "Expressa suas necessidades ou desejos de forma não verbal?",
  compreendeGestos:
    "Compreende quando você se comunica através de gestos com ele(a)?",
  usouComoFerramenta:
    'Alguma vez ele já te usou como "ferramenta" para indicar o que queria?',
  // 9) SONO
  dormeSoOuAcompanhado: "Dorme só ou acompanhado?",
  idadeFoiSeparado: "Com que idade foi separado(a)?",
  dormeComQuantasPessoas: "Com quantas pessoas?",
  temCamaIndividual: "Tem cama individual?",
  acordaVaiParaCamaPais: "Quando acorda vai para a cama dos pais?",
  temMedoDeDormirSozinho: "Tem medo de dormir sozinho?",
  vaiSozinhoParaCama: "Vai sozinho para a cama?",
  condicoesParaAdormecer: "Condições para adormecer:",
  temInsonia: "Tem insônia?",
  temSonoInterrompido: "Tem sono interrompido?",
  choraANoite: "Chora à noite?",
  gritaDuranteSono: "Grita durante o sono?",
  falaDormindo: "Fala dormindo?",
  rangeDentes: "Range os dentes?",
  movimentaMuitoSono: "Movimenta-se muito durante o sono?",
  // 10) CONDUTA E COMPORTAMENTO
  usaChupeta: "Usa chupeta?",
  ateQuandoChupeta: "Até quando:",
  chupaDedo: "Chupa o dedo?",
  ateQuandoDedo: "Até quando:",
  consegueImitar: "Consegue imitar sons, palavras e movimentos?",
  apresentaMudancasExpressaoFacial:
    "Apresenta mudanças na expressão facial, postura e conduta diante de uma resposta emocional?",
  moveComMesmaAgilidade:
    "Move-se com a mesma agilidade, facilidade e coordenação de uma criança da mesma idade?",
  demonstraInteresseBrinquedos:
    "Demonstra interesse por brinquedos e outros objetos?",
  usaExploraFuncionalmenteBrinquedos:
    "Faz uso e explora funcionalmente nos brinquedos e objetos?",
  carregaObjetoEspecifico:
    "Carrega ou sempre leva com ela algum brinquedo ou objeto específico?",
  quaisBrinquedos: "Quais?",
  ondeGostaBrincar: "Onde gosta de brincar?",
  temCuidadoComBrinquedos: "Tem cuidado com os brinquedos?",
  gostaTelevisao: "Gosta de televisão?",
  gostaHistorias: "Gosta de histórias?",
  praticaEsportes: "Pratica esportes?",
  quaisEsportes: "Quais",
  aceitaMudancasRotina: "Aceita mudanças na rotina?",
  possuiContatoVisualPessoas: "Possui contato visual com as pessoas?",
  possuiContatoVisualObjetos: "Possui contato visual com objetos?",
  possuiRespostaAuditivaAdequada:
    "Possui resposta auditiva adequada para a idade?",
  apresentaMedoNervosismoAdequados:
    "O educando apresenta medo e nervosismos adequados para a situação e a idade?",
  nivelAtividade: "Qual o nível de atividade do educando?",
  expressaDores: "Expressa dores ou desconforto?",
  bateCabeca: "Bate a cabeça?",
  batePes: "Bate os pés?",
  arrancaCabelos: "Arranca os cabelos?",
  comportamentoEstereotipado: "Possuí algum comportamento estereotipado?",
  agrideSe: "Agride-se de alguma forma?",
  qualAgressao: "Qual?",
  comoReageAOrdens: "Como reage a ordens?",
  atendeComDoceOuSeveridade:
    "Atende melhor quando é repreendido com doçura ou severidade?",
  eAgressivo: "É agressivo?",
  descricaoAgressividade: "Descreva a agressividade que apresenta:",
  eTeimoso: "É teimoso?",
  eCarinhoso: "É carinhoso?",
  eAutoritario: "É autoritário?",
  eDependente: "É dependente?",
  quaisSituacoesDependencia: "Quais situações?",
  // 11) REPERTÓRIO SOCIAL
  apresentaTimidezAdequada: "Apresenta timidez adequada para sua idade?",
  demonstraIndiferenca: "Demonstra indiferença diante de outras pessoas?",
  necessarioTentativasParaAtencao:
    "São necessárias tentativas persistentes para conseguir a atenção do educando?",
  possuiAmigos: "Possui amigos?",
  prefereColegasIdadeSexo: "Prefere colegas de que idade e sexo?",
  fazAmizadeFacilmente: "Faz amizade facilmente?",
  brincaCooperativamente: "Brinca cooperativamente?",
  // 12) COMO É O RELACIONAMENTO
  relacionamentoMaeFilho: "Mãe e filho:",
  relacionamentoPaiFilho: "Pai e Filho:",
  relacionamentoIrmaos: "Irmãos:",
  relacionamentoColegasEscola: "Colegas da escola:",
  tratadoDiferenteDosOutros: "O educando é tratado diferente dos outros?",
  posicaoPaisDificuldade: "Posição dos pais diante da dificuldade da criança?",
  // 13) SEXUALIDADE
  demonstrouCuriosidadeSexual:
    "Já demonstrou algum tipo de curiosidade sexual?",
  atitudePaisSexualidade: "Qual atitude dos pais?",
  idadeCuriosidade: "Qual idade?",
  atitudeFamilia: "Qual foi a atitude da família?",
  executaAbertamenteOculta: "Executa tais atividades abertamente ou as oculta?",
  educacaoSexual: "Foi feita educação sexual?",
  // 14) SAÚDE
  saudeAtualmente: "Saúde atualmente?",
  doencasInfantis: "Doenças infantis e idades:",
  acompanhamentoMedico: "Acompanhamento médico?",
  ultimaConsulta: "Data da última consulta:",
  tomaMedicamento: "Toma algum medicamento?",
  quaisMedicamentos: "Quais?",
  houveInternacoes: "Já houveram internações?",
  motivoInternacao: "Motivo:",
  cirurgias: "Cirurgias?",
  motivoCirurgias: "Motivo:",
  tratamentosRealizados:
    "Tratamentos realizados (fonoaudiólogo, psicólogo....)",
  qualTratamento: "Qual?",
  problemasVisao: "Problemas de visão?",
  problemasAudicao: "Audição?",
  // 15) ANTECEDENTES FAMILIARES
  doencasDeficienciasFamiliares:
    "Doenças, deficiências, epilepsia, alcoolismo/drogas?",
  // 16) ESCOLARIDADE
  escolaFrequenta: "Qual escola frequenta?",
  anoEscolar: "Ano:",
  periodoEscolar: "Período:",
  gostaDeEscola: "Gosta de escola?",
  fezPreEscola: "Fez Pré-Escola?",
  turmaApoioSegundoProfessor: "A turma tem apoio de segundo professor?",
  rendimentoEscolar: "Qual seu rendimento escolar?",
  comportamentoSalaAula: "Comportamento em sala de aula:",
  // 17) EXAMES E AVALIAÇÕES
  examesAvaliacoes:
    "Detalhe abaixo os exames e avaliações, sintetizando os resultados, que seu filho(a) já realizou ou irá realizar:",
};

export const secoesAnamneses = [
  {
    titulo: "1) INFORMAÇÕES DE DADOS PESSOAIS",
    campos: [
      "nome",
      "idade",
      "dataNascimento",
      "naturalidade",
      "nacionalidade",
      "nomeMae",
      "idadeMae",
      "profissaoMae",
      "nomePai",
      "idadePai",
      "profissaoPai",
      "irmaos",
    ],
  },
  {
    titulo: "2) QUEIXA PRINCIPAL",
    campos: ["queixaPrincipal", "sexo"],
  },
  {
    titulo: "3) GESTAÇÃO E CONCEPÇÃO",
    campos: [
      "queriaEngravidar",
      "gestacao",
      "fezPreNatal",
      "periodoGestacao",
      "apgar",
      "fezIngestaoToxicos",
      "parto",
      "cordaoUmbilical",
      "chorouAoNascer",
    ],
  },
  {
    titulo: "4) AMAMENTAÇÃO E ALIMENTAÇÃO",
    campos: [
      "mamouPeito",
      "mamouPeitoAteIdade",
      "hojeTemHoraParaComer",
      "comeComIndependencia",
      "desdeIdadeCome",
      "fazUsoTalher",
      "derramaAlimentos",
      "comemJuntos",
      "porqueNaoComeJunto",
      "recursosMesa",
      "restricaoAlimentar",
      "quaisRestricoes",
    ],
  },
  {
    titulo: "5) DESENVOLVIMENTO PSICOMOTOR",
    campos: [
      "idadePsicomotor",
      "engatinhou",
      "fixouCabeca",
      "sorriu",
      "sentouSozinho",
      "andouSozinho",
      "caiaMuito",
    ],
  },
  {
    titulo: "6) CONTROLE DE ESFÍNCTERES",
    campos: [
      "controleEsfincteres",
      "idadeParouFraldas",
      "controlaFezesDiurnas",
      "controlaFezesNoturnas",
      "controlaUrinaDiurnas",
      "controlaUrinaNoturnas",
      "pedeParaIrOuVaiSozinho",
      "tomaBanhoSozinho",
      "vesteSeSozinho",
      "usaFraldas",
      "tentouTirarFraldas",
      "dificuldadesEncontradas",
    ],
  },
  {
    titulo: "7) COMUNICAÇÃO VERBAL",
    campos: [
      "falaFuncional",
      "primeirasPalavrasIdade",
      "falaFrasesCompletas",
      "anosFrases",
      "falaSignificativa",
      "entendeFala",
      "temComecoMeioEFim",
      "consegueDarRecado",
      "consegueManterDialogo",
      "questionamentosExcessivos",
      "linguagemIncompreensivel",
      "emiteGritos",
      "ecolalia",
      "usoPersistentePalavrasFrases",
      "gagueira",
      "trocaDeLetras",
    ],
  },
  {
    titulo: "8) COMUNICAÇÃO NÃO-VERBAL",
    campos: [
      "indicaApontando",
      "expressaNaoVerbalmente",
      "compreendeGestos",
      "usouComoFerramenta",
    ],
  },
  {
    titulo: "9) SONO",
    campos: [
      "dormeSoOuAcompanhado",
      "idadeFoiSeparado",
      "dormeComQuantasPessoas",
      "temCamaIndividual",
      "acordaVaiParaCamaPais",
      "temMedoDeDormirSozinho",
      "vaiSozinhoParaCama",
      "condicoesParaAdormecer",
      "temInsonia",
      "temSonoInterrompido",
      "choraANoite",
      "gritaDuranteSono",
      "falaDormindo",
      "rangeDentes",
      "movimentaMuitoSono",
    ],
  },
  {
    titulo: "10) CONDUTA E COMPORTAMENTO",
    campos: [
      "usaChupeta",
      "ateQuandoChupeta",
      "chupaDedo",
      "ateQuandoDedo",
      "consegueImitar",
      "apresentaMudancasExpressaoFacial",
      "moveComMesmaAgilidade",
      "demonstraInteresseBrinquedos",
      "usaExploraFuncionalmenteBrinquedos",
      "carregaObjetoEspecifico",
      "quaisBrinquedos",
      "ondeGostaBrincar",
      "temCuidadoComBrinquedos",
      "gostaTelevisao",
      "gostaHistorias",
      "praticaEsportes",
      "quaisEsportes",
      "aceitaMudancasRotina",
      "possuiContatoVisualPessoas",
      "possuiContatoVisualObjetos",
      "possuiRespostaAuditivaAdequada",
      "apresentaMedoNervosismoAdequados",
      "nivelAtividade",
      "expressaDores",
      "bateCabeca",
      "batePes",
      "arrancaCabelos",
      "comportamentoEstereotipado",
      "agrideSe",
      "qualAgressao",
      "comoReageAOrdens",
      "atendeComDoceOuSeveridade",
      "eAgressivo",
      "descricaoAgressividade",
      "eTeimoso",
      "eCarinhoso",
      "eAutoritario",
      "eDependente",
      "quaisSituacoesDependencia",
    ],
  },
  {
    titulo: "11) REPERTÓRIO SOCIAL",
    campos: [
      "apresentaTimidezAdequada",
      "demonstraIndiferenca",
      "necessarioTentativasParaAtencao",
      "possuiAmigos",
      "prefereColegasIdadeSexo",
      "fazAmizadeFacilmente",
      "brincaCooperativamente",
    ],
  },
  {
    titulo: "12) COMO É O RELACIONAMENTO",
    campos: [
      "relacionamentoMaeFilho",
      "relacionamentoPaiFilho",
      "relacionamentoIrmaos",
      "relacionamentoColegasEscola",
      "tratadoDiferenteDosOutros",
      "posicaoPaisDificuldade",
    ],
  },
  {
    titulo: "13) SEXUALIDADE",
    campos: [
      "demonstrouCuriosidadeSexual",
      "atitudePaisSexualidade",
      "idadeCuriosidade",
      "atitudeFamilia",
      "executaAbertamenteOculta",
      "educacaoSexual",
    ],
  },
  {
    titulo: "14) SAÚDE",
    campos: [
      "saudeAtualmente",
      "doencasInfantis",
      "acompanhamentoMedico",
      "ultimaConsulta",
      "tomaMedicamento",
      "quaisMedicamentos",
      "houveInternacoes",
      "motivoInternacao",
      "cirurgias",
      "motivoCirurgias",
      "tratamentosRealizados",
      "qualTratamento",
      "problemasVisao",
      "problemasAudicao",
    ],
  },
  {
    titulo: "15) ANTECEDENTES FAMILIARES",
    campos: ["doencasDeficienciasFamiliares"],
  },
  {
    titulo: "16) ESCOLARIDADE",
    campos: [
      "escolaFrequenta",
      "anoEscolar",
      "periodoEscolar",
      "gostaDeEscola",
      "fezPreEscola",
      "turmaApoioSegundoProfessor",
      "rendimentoEscolar",
      "comportamentoSalaAula",
    ],
  },
  {
    titulo: "17) EXAMES E AVALIAÇÕES",
    campos: ["examesAvaliacoes"],
  },
];
